### ISSUE TITLE
not support vue 4

### ISSUE THREAD

**Issue by wdsmaduranga** [hantrongbinh/vue-country-code#37]
e-country-dropdown.js:2336 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.__vue_render__2 (vue-country-dropdown.js:2336:24)
    at renderComponentRoot (runtime-core.esm-bundler.js:914:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5649:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at instance.update (runtime-core.esm-bundler.js:5763:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5777:9)
    at mountComponent (runtime-core.esm-bundler.js:5559:9)
    at processComponent (runtime-core.esm-bundler.js:5517:17)
    at patch (runtime-core.esm-bundler.js:5119:21)
    at mountChildren (runtime-core.esm-bundler.js:5303:13)
_

**Comment by TheMaksKryt** [comment]
Vue 4?
